@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package jakojaannos.townbuilder.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;