@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package jakojaannos.townbuilder.client.settings;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;