@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package jakojaannos.townbuilder.client.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;