@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package jakojaannos.townbuilder.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;